#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import sys
import csv
import pathlib
from Bio import AlignIO
from Bio.Alphabet.IUPAC import ExtendedIUPACProtein
from makepotts.potts_object import *


def fasta2indices(alignment_handle, start_at_1=False):
    align = AlignIO.read(alignment_handle, 'fasta')
    tuple_list=[]
    assert(len(align) == 2)
    if start_at_1:
        pos0, pos1 = 0, 0
    else:
        pos0, pos1 = -1, -1
    for pair in zip(align[0].seq, align[1].seq):
        aligned_residues = True
        if pair[0].upper() in ExtendedIUPACProtein.letters:
            pos0 += 1
        else:
            aligned_residues = False
        if pair[1].upper() in ExtendedIUPACProtein.letters:
            pos1 += 1
        else:
            aligned_residues = False
        if aligned_residues:
            tuple_list.append((pos0, pos1))
    return tuple_list


def fasta2csv(alignment_handle, output_handle, potts_objects=[], start_at_1=False):
    tuple_list = fasta2indices(alignment_handle, start_at_1=start_at_1)
    csv_writer = csv.writer(output_handle)
    csv_writer.writerow(['pos_ref','pos_2'])
    if len(potts_objects)==2:
        seq_pos_to_mrf_pos = [obj.get_seq_pos_to_mrf_pos() for obj in potts_objects]
    else:
        seq_pos_to_mrf_pos = None
    for pair in tuple_list:
        if seq_pos_to_mrf_pos is not None:
            pair = [seq_pos_to_mrf_pos[k][pair[k]] for k in range(2)]
        if (pair[0] is not None) and (pair[1] is not None):
            csv_writer.writerow(pair)
        else:
            print(pair, "was not aligned")



def main(args=sys.argv[1:]):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'input_alignment', help='Pairwise alignment in fasta format',
        type=argparse.FileType('r')
    )
    parser.add_argument(
        'output_csv', help='Output file in (csv)',
        type=argparse.FileType('w')
    )
    parser.add_argument('-f', '--potts_folders', help="Potts objects (folders generated by MakePotts)", type=pathlib.Path, nargs='+', default=[])
    args = vars(parser.parse_args(args))

    
    potts_objects=[Potts_Object.from_folder(potts_folder) for potts_folder in args["potts_folders"]]
    fasta2csv(args['input_alignment'], args["output_csv"], potts_objects)


if __name__ == '__main__':
    main()
